name: loggy
description: Logger for Dart applications, use mixin for easier separation when needed
version: 2.0.1+1
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  stack_trace: '>=1.10.0 <2.0.0'

dev_dependencies:
  test: '>1.1.0 <2.0.0'
